### ISSUE TITLE
Ribo-seq Template

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/sysbioDCCjsonschemas#11]
_31Jan2020 email to Xusheng Wang (xusheng.wang@und.edu)_

Hello Xusheng!

I'm working with our PsychENCODE collaborators to develop metadata templates for assay data.  Since your lab is going to be submitting Ribo-Seq data soon (per the answers to the data submission survey that we sent out late last year), we'd like your input on the metadata that would be necessary for other investigators to have in order to utilize that data.

I'm attaching the RNA-Seq metadata template as basis for developing the Ribo-Seq template.  We'd like you to use it to give us the following information:

1) Are there any columns in the RNA-Seq template that are unnecessary/superfluous for the Ribo-Seq assay?
2) Are there any other data columns that are essential to the Ribo-Seq assay that would need to be added?

We would appreciate your feedback on this by next Friday (07Feb2020) if possible so that we can have the template in place for you to be able to utilize when you are ready to upload your data.

Please let me know if you have any questions.

Thanks for your help!
Cindy

**Comment by cw-dvr8** [comment]
_31Jan2020 email from Xusheng_

Hi Cindy,

Thanks for the template. I just want to clarify a little bit that the data that I am going to submit are proteomic data. Thanks!

Xusheng

**Comment by cw-dvr8** [comment]
_31Jan2020 email to Xusheng_

Thanks for getting back to me on this.  We do see that you will be submitting proteomics data according to the survey, but it also says that you will be submitting Ribo-Seq data.  It sounds like that may have been mistakenly checked?

**Comment by cw-dvr8** [comment]
_06Feb email from Xusheng_

Hi Cindy,

If you have any questions about Ribo-seq data, would you please contact Annie? I include her in this email loop. Thanks!

Xusheng

**Comment by cw-dvr8** [comment]
_11Feb email to Annie Shieh (sanninnas@gmail.com)_

Hi Annie.  I'm a data curator at Sage Bionetworks working with the PsychENCODE consortium, and I was referred to you by Xusheng Wang.  We're trying to develop a Ribo-Seq assay metadata template and are looking for input on what sort of metadata would be necessary for other investigators to have in order to utilize Ribo-Seq assay data.  A survey that we sent out to the PsychENCODE consortium late last year shows that you plan on submitting this data, so I'm attaching our RNA-Seq metadata template and would like you to use if to give us the following information:

1) Are there any columns in the RNA-Seq template that are unnecessary/superfluous for the Ribo-Seq assay?
2) are there any other metadata columns that are essential to the Ribo-Seq assay that would need to be added?

I'd appreciate your feedback on this by next Friday (21Feb2020) if possible so that we can have the template in place for you to be able to utilize when you are ready to upload your data.

Please let me know if you have any questions.

Thanks!
Cindy Molitor

**Comment by cw-dvr8** [comment]
_11Feb email to Annie Shieh (cc'ed Chunyu Liu)_

Hi Annie, I hadn't heard anything from you so I thought I would check in.  We would like to have our Ribo-Seq metadata template in place when you are ready to upload your PsychENCODE Ribo-Seq data, so we would really appreciate your feedback on what sort of information other investigators would need to know in order to use it.  I'm attaching our RNAseq template, and it would be very helpful to us if you would review it and let us know:

a) which columns would not be applicable to Ribo-Seq.
b) if there are any columns that should be added to collect information for Ribo-Seq.

Please let me know if you have any questions.

Thanks!
Cindy

**Comment by cw-dvr8** [comment]
_26Feb2020 email from Annie Shieh_

Hi Cindy,
Sorry I missed this. 
We have previously uploaded the riboseq data (fastq and bam files) with accompanying metadata (syn11969366 and syn12214175). Could you let me know if this is to upload the data elsewhere or that our previous uploads need to be edited?
Many thanks,
Annie

**Comment by cw-dvr8** [comment]
_06Mar2020 email to Annie Shieh_

Hi Annie.

My questions about Ribo-Seq data are because we (Sage Bionetworks) sent out a data contribution survey late last year to see who was planning to contribute data by the end of March 2020, and we got a response that your lab would be sending in new Ribo-Seq data.  If this isn't the case, let me know and I will remove that expectation.

With that said, we have implemented a new app called the dccvalidator (https://shinypro.synapse.org/users/kmontgomery/dccvalidator/) to help us standardize the metadata that is used to annotate the data files that are uploaded.  We now have standard metadata templates for individuals, biospecimens, and some assays, but need to develop a standardized template that researchers can use to submit information about their Ribo-Seq assay data.  Since you are familiar with this assay, we are hoping that you can provide guidance to us about what information would be useful for others to know about the data so that we can build a template and use this information to annotate data files.  I'm attaching our RNAseq metadata template here for you to use as a base to modify as appropriate to accommodate Ribo-Seq metadata.  Please feel free to either delete columns that would not be applicable for this assay, or to add columns for any information that you feel it would be important for others to know about.

Also, while it is not necessary to re-upload your data files, we are going to need you to resubmit the metadata that you'd previously sent along with your Ribo-Seq data.  The individual metadata template is here: https://www.synapse.org/#!Synapse:syn20781820 , and the biospecimen template is here: https://www.synapse.org/#!Synapse:syn20768131 .  Once we have a standard metadata template for Ribo-Seq, we would also need you to go back and complete that as well.  The dccvalidator app has usage instructions in the link that I provided above, and we also have a Zoom training meeting on how to use the dccvalidator and the templates scheduled for Wednesday (11Mar) at 11:00 Pacific time.  I can send you an invitation for it if you have not received one already.

I hope this helps answer your questions, and I apologize for any confusion my earlier email might have caused.  Please feel free to contact me if you have any other questions.

Thanks!
Cindy

**Comment by cw-dvr8** [comment]
_06Mar email from Chunyu Liu, cc Annie Shieh and Mette_

All our riboseq data have been uploaded, as I know.
Chunyu

**Comment by cw-dvr8** [comment]
_06Mar email to Chunyu Liu, cc Annie Shieh and Mette_

Thanks for your response!  I'll go ahead and remove that expectation.

Note that we will still need to have the metadata for your previous submission updated, and we would still appreciate your help in developing a Ribo-Seq metadata template for future uploads.

Thanks!
Cindy

**Comment by cw-dvr8** [comment]
06Mar2020 - Removed the Ribo-Seq expectation for Chunyu Liu's lab from the PsychENCODE Data Contribution Responses table (syn21295390).  There are no other Ribo-Seq expectations from any other labs for the end of March.

**Comment by cw-dvr8** [comment]
_09Mar2020 email from Annie Shieh_

Hi Cindy,
I've attached a modified metadata template for Riboseq
Let me know if you have any comments/questions
Thanks,
Annie

**Comment by cw-dvr8** [comment]
26Mar2020: Emailed template to @amapeters for review.

**Comment by amapeters** [comment]
[template_assay_Ribo-Seq (1).xlsx](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/files/4738217/template_assay_Ribo-Seq.1.xlsx)
Assuming this is the correct template, it looks like the recommended variables are a subset of the RNAseq. Can we just use the RANseq template? Did Annie add anything new?

**Comment by cw-dvr8** [comment]
@kelshmo Can you tell me what fields the dccvalidator is expecting for RNAseq, and whether it would cause problems if we used the RNAseq template to submit ribo-seq data?  Ribo-seq uses only a subset of the RNAseq fields, so if the dccvalidator is expecting fields that ribo-seq doesn't need, we'll have to come up with a separate template for it.

**Comment by kelshmo** [comment]
I don't require columns in an assay-specific manner. Here are the [required columns for assay](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/config.yml#L147-L152). Otherwise there is a warning for missing columns as defined by the [assay templates](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/config.yml#L115-L122).

**Comment by cw-dvr8** [comment]
@kelshmo The ribo-seq template would be lacking the required libraryPrep column.  The TMTquantitation and snpArray also don't have this column.  What is the mechanism by with they pass the dccvalidator?

**Comment by kelshmo** [comment]
We can remove it as a requirement - haven't run into a problem.

**Comment by cw-dvr8** [comment]
@amapeters Currently libraryPrep is required for all assays, but it is not required for ribo-seq.  @kelshmo can remove it as a requirement and then we would be able to use the RNAseq template to get ribo-seq metadata.  What do you think?

**Comment by kelshmo** [comment]
I went ahead and removed all requirements - preserving `specimenID`

**Comment by cw-dvr8** [comment]
No new template - using the rnaSeq template.
