### ISSUE TITLE
create value for test: test

### ISSUE THREAD

**Issue by avanlinden** [Sage-Bionetworks/sysbioDCCjsonschemas#129]
**For term:** Testing 1-2-3. Does this auto assign to Juliane?

Proposed value: <value>
- Definition:
- Source: 

_(Optional)_ Linked issues, contributor requests, or other information: <more info> 

**To do:**
- [ ] data coordinator provides value, definition, and source in this issue, then assigns to relevant DCC curator
- [ ] curator has added value to [synapseAnnotations repo](https://github.com/Sage-Bionetworks/synapseAnnotations)

**Comment by danlu1** [comment]
I think the issue has been automatically assigned to Juliane.
