### ISSUE TITLE
update ATACSeq template to include scATACSeq values

### ISSUE THREAD

**Issue by avanlinden** [Sage-Bionetworks/sysbioDCCjsonschemas#137]
## _Single-cell ATAC-seq data are sparse and noisy_

Article on scATACSeq methods: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02075-3
Existing template (ATACSeq): https://www.synapse.org/#!Synapse:syn22024364
Requested template: scATACSeq

Current [ATACseq assay metadata](https://github.com/Sage-Bionetworks/sysbioDCCjsonschemas/blob/master/schema_metadata_templates/shared/assay_ATACSeq_metadata_template.json) keys:

specimenID | libraryID | assay | platform | referenceSet | transposaseBatch | libraryBatch | libraryPreparationMethod | pcrCycles | sequencingBatch | isStranded | readStrandOrigin | readLength | runType | meanCoverage | meanGCContent

Keys suggested by data contributors:

Q30 bases in read 1
Q30 bases in read 2
barcode
sample index

**Comment by avanlinden** [comment]
Moved [this issue](https://github.com/Sage-Bionetworks/synapseAnnotations/issues/911) here since it concerns metadata template updates for SysBio projects.

**Comment by pitviper6** [comment]
@avanlinden This? https://support.10xgenomics.com/single-cell-atac/sequencing/doc/specifications-sample-index-sets-for-single-cell-atac

**Comment by avanlinden** [comment]
@pitviper6 Oh interesting -- so basically you need the oligos in this 10x mapping file to link reads to the sample they came from. I wonder if there is something analogous used in non-10x brand assays (not sure if other scATACseq will be done with 10x kits). Also, how does the sample index differ from the barcode?

**Comment by avanlinden** [comment]
@tmzintel We have a contributor who is providing single-cell ATACseq data and we are discussing how to update our current bulk ATACseq assay metadata template to accommodate the single cell data. Specifically, Juliane has been asking the data contributor about what additional terms they think are necessary to capture. If you have any thoughts on useful single-cell metadata we would love to hear them!

**Comment by danlu1** [comment]
Don't have much to contribute but do we need to add version? It seems for different version they use different sample index

**Comment by pitviper6** [comment]
@danlu1 Please add the following keys to the current ATACseq template (https://www.synapse.org/#!Synapse:syn20768526):
 * Q30BasesinRead1
    * datatype: decimal (percentage)
    * Definition: The Q30 value provides the percentage of bases sequenced with a Phred score of at least 30, corresponding to an error rate of 0.1%.
    * Source: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7826284/
 * Q30BasesinRead2
    * datatype: decimal (percentage)
    * definition: The Q30 value provides the percentage of bases sequenced with a Phred score of at least 30, corresponding to an error rate of 0.1%.
    * Source:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7826284/
 * barcode
   * datatype:  number
   * definition: A machine-readable representation of information in a visual format on a surface. [ NCI ]
   * source: http://purl.obolibrary.org/obo/NCIT_C43361
 * sample index 
   * datatype: text
   * definition: Chromium sample indexes each comprise four oligonucleotides. When analyzing Chromium sequencing data for a given sample, you must combine the reads associated with all four of the oligonucleotides in the sample index.
    * source: https://support.10xgenomics.com/single-cell-atac/sequencing/doc/specifications-sample-index-sets-for-single-cell-atac

**Comment by avanlinden** [comment]
@pitviper6 I have a couple of thoughts on these terms --

- There's already a term in our dictionary for `sampleBarcode`, which I think will work here as well, so we don't need to add "barcode". 
- For "sample index", do we want to do it in camel case? It's not like we're terribly consistent with but to match the other terms maybe `sampleIndex`?
- I still don't have a sense of whether the sample index oligos are used in other scATAC sequencing kits. If it's specific to 10x maybe a better key would be `ChromiumSampleIndex`? Don't know whether to err on the side of too specific or too general here.

**Comment by pitviper6** [comment]
@avanlinden @danlu1 
1. Agreed, let's use the existing sampleBarcode for this template
2. Agreed, let's use camel cade
3. I'd rather err on the general. It helps discoverability and it should be evident from the methods that it's chromium

**Comment by avanlinden** [comment]
@pitviper6 all sounds good to me!

**Comment by pitviper6** [comment]
@danlu1 
Here is the revised keys for the ATACseq template. I did some more research and decided to go with chromiumSampleIndex because I couldn't find a good definition for just sampleIndex, and all the publications seem to tie it to chromium

Please add the following keys to the current ATACseq template (https://www.synapse.org/#!Synapse:syn20768526):
 * Q30BasesinRead1
    * datatype: decimal (percentage)
    * Definition: The Q30 value provides the percentage of bases sequenced with a Phred score of at least 30, corresponding to an error rate of 0.1%.
    * Source: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7826284/
 * Q30BasesinRead2
    * datatype: decimal (percentage)
    * definition: The Q30 value provides the percentage of bases sequenced with a Phred score of at least 30, corresponding to an error rate of 0.1%.
    * Source:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7826284/
 * sampleBarcode
   * This key already exists in the schema - please add it to the template 
 * chromiumSampleIndex 
   * datatype: text
   * definition: Chromium sample indexes each comprise four oligonucleotides. When analyzing Chromium sequencing data for a given sample, you must combine the reads associated with all four of the oligonucleotides in the sample index.
    * source: https://support.10xgenomics.com/single-cell-atac/sequencing/doc/specifications-sample-index-sets-for-single-cell-atac

**Comment by danlu1** [comment]
Done.
