### ISSUE TITLE
Enhancing discovery of multiome data

### ISSUE THREAD

**Issue by pitviper6** [Sage-Bionetworks/sysbioDCCjsonschemas#142]
Multiome data:
DC is performing scrnaSeq and scatacSeq on the same specimen. Methods: https://www.synapse.org/#!Synapse:syn29879329

How do we annotate for multiome data?

1. In the biospecimen metadata, the DC enters the assays that were performed on one biospecimen
2. For the assay metadata, the DC chooses one of the assay templates and adds columns as needed

Do we need a specific annotation that indicates multiome data, or is having the biospecimen linked to two (or more?) assays enough?

**Comment by avanlinden** [comment]
@pitviper6 I believe the best solution is to have a value for `libraryPrep` that is "multiome", and then as you suggested have the DC apply annotations to the multiome files with `isMultiome` = T/F just for easy filtering. That `isMultiome` key won't be a facet in the AD portal fileview, but it will help distinguish the files with advanced queries.

Does that sound ok?

**Comment by pitviper6** [comment]
@avanlinden that sounds fine!

**Comment by avanlinden** [comment]
great, values/terms added in this PR: https://github.com/Sage-Bionetworks/synapseAnnotations/pull/916
