### ISSUE TITLE
Changes to PEC schema - valid study

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/sysbioDCCjsonschemas#15]
- NeuREs is a valid study value. (The manifest performs this check).

This schema will need to be updated with every study added. We want to constrain this value to ensure harmony across our PEC resource! 

One option is to automate this list based on the [folder names present in this hierarchy](https://www.synapse.org/#!Synapse:syn5553626).

**Comment by cw-dvr8** [comment]
I've added the new studies but can't create a PR until PR #14 is resolved.

**Comment by cw-dvr8** [comment]
04Mar2020 - Pushed to production.
