### ISSUE TITLE
Case sensitive true/false values

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/sysbioDCCjsonschemas#16]
There are [cases](https://www.synapse.org/#!Synapse:syn20981788/tables/query/eyJzcWwiOiJTRUxFQ1Qga2V5LCBtb2R1bGUgRlJPTSBzeW4yMDk4MTc4OCB3aGVyZSB2YWx1ZSA9ICd0cnVlJyIsICJpbmNsdWRlRW50aXR5RXRhZyI6dHJ1ZSwgImlzQ29uc2lzdGVudCI6dHJ1ZSwgIm9mZnNldCI6MCwgImxpbWl0IjoyNX0=) in the individual/clinical data where true and false is case sensitive as these are string column types. This has caused confusion with researchers trying to validate. 

- Luckily, Synapse search is not case sensitive (e.g. TRUE, true, True all discoverable by a query on any capitalization). I can't think of an alternative solution - it feels like we must enumerate all allowed values with the variables we want to be explicit about "unknown".

**Comment by cw-dvr8** [comment]
If we're not worried about case, is there no way in the validator code to upcase or lowercase?  E.g. something like this:

if upper(_manifestValue_) = _upper(_controlledListValue_) then _etc. etc. etc._

**Comment by kelshmo** [comment]
Per discussion in [dccvalidator issue](https://github.com/Sage-Bionetworks/dccvalidator/issues/284#issuecomment-586437715): I think the work to develop novel code and test our code base in `dccvadliator` is too significant to deal with this edge case which only impacts 5 variables by my estimation. 

The problem is we allow the import functions to distinguish booleans (logical), character and numeric without specifying variable types explicitly. The read function reads a value postmortem  = true as boolean and when this value is checked against our annotations it fails as the check is case sensitive. 

My suggestion is to enumerate alternative capitalization for these 5 cases.

**Comment by kelshmo** [comment]
@cw-dvr8 are you able to enumerate alternative capitalization for the 5 cases?

**Comment by cw-dvr8** [comment]
@kelshmo the options I see are true, false, TRUE, FALSE, and unknown.  Are these all of the ones you currently see?

**Comment by cw-dvr8** [comment]
I was researching if there was a way to tell Excel to default the columns to text instead of Boolean, but it doesn't look like that approach is practical.

**Comment by kelshmo** [comment]
Also - True, False.

**Comment by cw-dvr8** [comment]
04Mar2020 - Refreshed the PEC Annotations Module table (syn20981788).
