### ISSUE TITLE
STARR-Seq assay metadata template

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/sysbioDCCjsonschemas#18]
_31Jan2020 email to Sophia Gaynor (sophia.gaynor@tempus.com)_

Hi Sophia!

I'm working with our PsychENCODE collaborators to develop metadata templates for assay data.  Since your lab is going to be submitting STARR-Seq data soon (per the answers to the data submission survey that we sent out late last year), we'd like your input on the metadata that would be necessary for other investigators to have in order to utilize that data.

I'm attaching the RNA-Seq metadata template as basis for developing the STARR-Seq template.  We'd like you to use it to give us the following information:

1) Are there any columns in the RNA-Seq template that are unnecessary/superfluous for the STARR-Seq assay?
2) Are there any other data columns that are essential to the STARR-Seq assay that would need to be added?

We would appreciate your feedback on this by next Friday (07Feb2020) if possible so that we can have the template in place for you to be able to utilize when you are ready to upload your data.

Please let me know if you have any questions.

Thanks for your help!
Cindy

**Comment by cw-dvr8** [comment]
_07Feb2020 email from Sophia Gaynor_

Hi Cindy, 

I sent the spreadsheet and your questions to Thomas Goodman (cc'd here). He does most of our data analysis, so he has a better feel for what columns are necessary. His response is below: 

1. I used the whole genome assay template instead.
The column libraryPreparationMethod could use the value STARR-SEQ.
libraryPrep could use a value something similar to: "electroporation of cells with ORI- library plasmid, extract RNA/mRNA, then RT to cDNA, then PCR amplify the library"
RIN score probably isn't a necessary column. 

2.
I think the columns that exist are enough. 

Hope that helps! Please let Thomas and myself know if you have any questions. 

Best,
Sophie

**Comment by cw-dvr8** [comment]
@amapeters , @kelshmo : See Thomas' comments above.

1) Should I go ahead and add STARR-SEQ to libraryPreparationMethod in our annotations?

2) Do you have any suggestions for a value that fits with what he wants to add to libraryPrep?

3) STARR-Seq needs to be added to assay in annotations.  I found this source: http://purl.obolibrary.org/obo/OBI_0002041 .  Let me know if this sound correct and I'll open a PR to add it to annotations.

**Comment by kelshmo** [comment]
>     1. Should I go ahead and add STARR-SEQ to libraryPreparationMethod in our annotations?
I suggest using the value `STARR-seq` and the [purl source you proposed](http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/OBI_0002041). 

>     2. Do you have any suggestions for a value that fits with what he wants to add to libraryPrep?
I think its possible that these samples used `polyAselection` but that would need to be clarified with the contributor. I don't think we need to add a value here. 

>     3. STARR-Seq needs to be added to assay in annotations.  I found this source: http://purl.obolibrary.org/obo/OBI_0002041 .  Let me know if this sound correct and I'll open a PR to add it to annotations.

Based on this correspondence with Sophia from September I think the assay should remain `rnaSeq`. This is corroborated by the purl reference you linked as RNA-seq is a super class there: 

> The output is actually RNAseq data. Basically the idea is that you clone putative enhancer regions into a reporter plasmid downstream of a minimal promoter and upstream of a poly-A site. You then transfect cells with that plasmid library and active enhancers will promote their own transcription. You isolate mRNA, convert to cDNA and sequence. Regions with a lot of reads represent active enhancers. So the end readout is still RNAseq.

**Comment by cw-dvr8** [comment]
@amapeters see the comments from @kelshmo above.  STARR-Seq is one of the assays on the survey, and I think it would cause confusion if we kept it as a separate assay there but told them to use the RNASeq template to submit their data.  Do you want to take STARR-Seq off of the survey, or do you want to keep it and have a separate STARR-Seq template that's the same as the RNASeq template, or do you have another option?

**Comment by amapeters** [comment]
I agree with taking it of the survey, and keeping the assay as RNAseq. Based on the definition (http://purl.obolibrary.org/obo/OBI_0002041) it should be added as  another libraryPrep value

**Comment by cw-dvr8** [comment]
Sounds good, I'll remove it from the survey and open a PR to add it as a value for libraryPrep.

**Comment by cw-dvr8** [comment]
04Mar2020 - Removed from the upcoming data contribution survey.  The term has been added to the values list for libraryPrep.
