### ISSUE TITLE
Naming metadata templates

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/sysbioDCCjsonschemas#81]
Bringing this discussion out of #80 PR for documenting the thought process and allowing that PR to be merged when approved.

**Background:** Some of our schemas will be specific to a group. For example, both PEC and AD will have manifest metadata template that is not shared between them. If we have the same name for both schemas, there will be a namespace clash.

**Current comments:**
@cw-dvr8:
> I'm thinking that for a naming convention for AD and PEC specific templates, we could put "AD" or "PEC" in front of the schema type, e.g. "PECassay.ChIPSeq" or "ADindividual.human". What do you think?

@Aryllen:
> Adding a specific naming convention to only the PEC and AD templates works for me. Can we separate them with a period for readability?
>
> PEC.assay.ChIPseq and AD.individual.human?

@avanlinden:
> I second the period for readability -- keeps it from being alphabet soup with the assays that are acronyms.

**Comment by cw-dvr8** [comment]
@Aryllen @avanlinden I wasn't sure whether Synapse would allow a three-part name, but I just test-registered one (sysbio.assayTemplates-PEC.Specific.manifest) and it didn't have a problem.  I'm therefore totally fine with adding PEC. and AD. to consortium-specific schemas.

**Comment by Aryllen** [comment]
Closing since it was agreed that adding 'ad' and 'pec' to the beginning of names works fine.
