### ISSUE TITLE
Proteomics assay template

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/sysbioDCCjsonschemas#9]
Per Mette, use the AMP-AD template:

https://www.synapse.org/#!Synapse:syn21433357

**Comment by cw-dvr8** [comment]
_11Feb2020 email to Xusheng Wang (xusheng.wang@und.edu)_

Thanks Xusheng.  In the meantime, I do have a question for you.  Is the proteomics data that you will be submitting TMT labeled proteomics?

Thanks!
Cindy

**Comment by cw-dvr8** [comment]
_11Feb2020 email from Xusheng_

Hi Cindy,

Yes. I will submit the TMT labeled proteomics data. The sample information will be the exact same as that submitted last time. The only difference for this new batch is that we have more raw files. Please send me instructions on how to submit raw data. Thanks!

Xusheng

**Comment by cw-dvr8** [comment]
_Slack convo with Kara Woo_

Cindy Molitor  1:00 PM
Mette asked me to make a proteomics assay schema from the TMTquantitation assay schema in AMP-AD.  I was looking at it, and it doesn't have "batch" and "batchChannel" defined in the dictionary.  Would you give me the definitions?

kara  1:24 PM
if it’s not there then I don’t think there is a definition
1:29
I looked back in my emails and don’t have any discussion of this, so i think we’d need to either ask mette or a collaborator and then add it to the definitions

Cindy Molitor  1:29 PM
Okay, I'll ask Mette and keep you in the loop.

**Comment by amapeters** [comment]
The batch channel refers to the batch the sample is in and the TMT channel the sample is labeled with. Samples for TMT proteomics are batched into sets of 8-16? samples (depends on the TMT kit) where each sample is labeled with a specific TMT channel.

**Comment by cw-dvr8** [comment]
@amapeters Okay, thanks for the clarification.

"batch" and "batchChannel" are somewhat generic.  Do we want to rename them, maybe to "TMTbatch"/"TMTBatchChannel"?

cc @karawoo

**Comment by cw-dvr8** [comment]
Have created the schema but can't create a PR until PR #14 is resolved.

**Comment by cw-dvr8** [comment]
04Mar2020 - Pushed to production.
